### ISSUE TITLE
请问在\src\views\topoGraph\index.vue中名为centerNode的数据应该是什么样的，可以给一个示例数据吗

### ISSUE THREAD

**Issue by Umasou-k** [fxzer/network-topology-graph#1]
例如在点击事件中：
graph.value.on("node:click", (e) => {
      const item = e.item;
      const model = item.getModel();
      centerNode.value = JSON.parse(JSON.stringify(model));
      topoVisible.value = true;
    });
可以给一个这里的model的示例数据吗，谢谢！

**Comment by fxzer** [comment]
![image](https://github.com/fxzer/network-topology-graph/assets/68853957/ddebe845-5095-4270-b286-b0cb0af12978)
可以的，这个centerNode是外面点击的节点，在打开的弹窗里充当中心点，点击的时候会在上面设置一些属性，比如 size，sysType（节点类型）等等，因为打开的弹窗，需要这些这些做不同的处理
